### ISSUE TITLE
engine language

### ISSUE THREAD

**Issue by Pantyhose-X** [AntonioNoack/RemsEngine#1]
Select a language to write the Game Engine. and mods：[Rust](https://github.com/rust-lang/rust)  [Zig](https://ziglang.org/)  [Nim](https://nim-lang.org/) [Nelua](https://nelua.io/)
Rust GUI: [Dioxus](https://dioxuslabs.com/) [tauri](https://github.com/tauri-apps/tauri)

---
### other
Similar to the [Minetest engine](https://github.com/minetest/minetest) written in C++
mods written using LuaJIT

**Comment by AntonioNoack** [comment]
What are you talking about? My game engine is written in **Kotlin**. It can be compiled to the Java Virtual Machine.
I have a secondary, private compiler, that kind of works, and compiles it to WASM.

If you would like to translate the whole engine, feel free to do so, but it will be >100k lines of code, and the code of my engine will probably continue to change.
As a scripting language, I have experimented with a visual language and Lua, and I think both (could) fit nicely.
Having a high level language for the engine (one without that many memory management worries), and low level like Rust for mods doesn't make much sense imo.

**Comment by AntonioNoack** [comment]
I'll be awaiting your answer, but probably close the issue then.

You had a pretty awkward comment on Tantan's Discord on Leddoo's project as well.
Rust is not better than Kotlin. You can't say that that universally. Both have their strengths. Rust may often be faster, but Kotlin is much easier to learn and to write.

**Comment by Pantyhose-X** [comment]
> You can't say that that universally. Both have their strengths. Rust may often be faster, but Kotlin is much easier to learn and to write.

Kotlin cross-platform PC is not good, Every language has its strengths and weaknesses. 
I agree with the use of high-level languages, You write less code
